#Config file
#These modules will be crunched to one.
#TODO: Need to support dictionary in the list;

#Global object and description
Global.js

#Reference
ref/Math.uuid.js

#WebSvr
RequestParser.js
SessionParser.js
Parser.js
Filter.js
Handler.js
WebSvr.js

#Testing Site
SiteTest.js