#Config file
#These modules will be crunched to one.
#TODO: Need to support dictionary in the list;

#Global object and description
Global.js
Settings.js
Logger.js

#Reference: JavaScript library
ref/Math.uuid.js

#WebSvr Modules
Mapper.js
RequestParser.js
SessionParser.js
Parser.js
Filter.js
Handler.js
ListDir.js
Template.js
Server.js